export const Members = [
  {
    id: 1,
    memberId: "MEM-A1B2C",
    fullName: "Aarav Sharma",
    post: "President",
    email: "aarav@csitabmc.edu.np",
    facebookLink: "",
    linkedinLink: "",
    githubLink: "",
    tags: ["Leadership", "Event Management"],
    description: "Club president and founding member.",
    image: null,
    status: "active",
    createdAt: "2025-01-10",
  },
  {
    id: 2,
    memberId: "MEM-D3E4F",
    fullName: "Priya Thapa",
    post: "Technical Lead",
    email: "priya@csitabmc.edu.np",
    facebookLink: "",
    linkedinLink: "",
    githubLink: "https://github.com/priyathapa",
    tags: ["React", "Node.js"],
    description: "Leads all technical initiatives.",
    image: null,
    status: "active",
    createdAt: "2025-02-14",
  },
  {
    id: 3,
    memberId: "MEM-G5H6I",
    fullName: "Rohan Bista",
    post: "Design Lead",
    email: "rohan@csitabmc.edu.np",
    facebookLink: "",
    linkedinLink: "",
    githubLink: "",
    tags: ["UI/UX", "Figma"],
    description: "Responsible for all design assets.",
    image: null,
    status: "draft",
    createdAt: "2025-03-01",
  },
];

export const POST_OPTIONS = [
  "President",
  "Vice President",
  "Secretary",
  "Treasurer",
  "Event Coordinator",
  "Tech Lead",
  "Assistant Tech Lead",
  "Design Lead",
  "Member",
];
